### ISSUE TITLE
System call gets encoded into Format 2.5.1, which the manual doesn't mention

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/bintools#10]
The only system call in the 2.5.X group mentioned there is 2.5.7.

I am not sure if I should file these issues here or in the manual, but as I tend to view the manual as the source of truth, I am filing them here for now.

**Comment by AgnerF** [comment]
System call in format 2.5.1B is allowed. This is an omission in the manual. I will be added in the next version of the manual. This call has 16 bits function ID and 16 bits module ID in the lower and upper halves of IM2.
