### ISSUE TITLE
add/jump does not add negative immediates from -33 to -64

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/bintools#11]
-32 and up, as well as -65 and below, work.

**Comment by AgnerF** [comment]
Please provide an example. I cannot reproduce this error

**Comment by Kulasko** [comment]
This produces an infinite loop when emulated:
```
int32 r7 = 256
@beginning:
int32 r7 = add(r7, -64), jump_pos @beginning
```
After your fix for the sub_jump instructions, this now produces an infinite loop as well since it's converted to an add_jump:
```
int32 r7 = 256
@beginning:
int32 r7 = sub(r7, 64), jump_pos @beginning
```
The debug listing of the emulator suggests that the negative constant is just not applied.

**Comment by AgnerF** [comment]
Oh, it's the emulator. I thought you meant the assembler.
Fixed emulator1.cpp

**Comment by Kulasko** [comment]
The issue seems fixed. Thank you for your work.
